name: Robot
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  exec:
    if: false
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: boost
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev
      # - name: Install chromium
      #   if: matrix.os == 'ubuntu-20.04'
      #   # https://launchpad.net/ubuntu/+source/chromium-browser/101.0.4951.64-0ubuntu0.18.04.1
      #   run: sudo apt-get install chromium-browser=101.0.4951.64
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run robot
        run: xvfb-run npm run exec
      - uses: actions/upload-artifact@v4
        with:
          name: nesting
          path: /home/runner/
          retention-days: 1
